// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lknuzpoodcqrdopgyrlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrbnV6cG9vZGNxcmRvcGd5cmxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMzc1MTYsImV4cCI6MjA3NTcxMzUxNn0.inE9_Bc1t95O3nzGHQZyGZTSyvdQcbc8GbKRt0DovPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});